tiles.loadMap(tiles.createMap(tilemap`home`))
let pet_carer = sprites.create(assets.image`player`, SpriteKind.Player)
controller.moveSprite(pet_carer)
scene.cameraFollowSprite(pet_carer)
tiles.placeOnRandomTile(pet_carer, assets.tile`myTile0`)
tiles.coverAllTiles(assets.tile`myTile0`, assets.tile`myTile`)
tiles.coverAllTiles(tiles.util.door5, assets.tile`myTile`)
let puppy1 = sprites.create(assets.image`puppy1`, SpriteKind.Player)
let dog1 = sprites.create(assets.image`dog2`, SpriteKind.Player)
let cat1 = sprites.create(assets.image`kitten1`, SpriteKind.Player)
